import { NativeDatabaseService } from '../services/native-db-service'

/**
 * Validates SQL to prevent potentially destructive operations.
 * @param sql The SQL string to validate.
 * @returns True if the SQL is safe to execute, otherwise throws an error.
 */
function validateSQL(sql: string): boolean {
  // A simple check for read-only commands.
  const trimmedSql = sql.trim()
  const upperSql = trimmedSql.toUpperCase()

  // [Smart Metrics & Introspection] Allow View Creation, DESCRIBE, and PRAGMA
  // Use regex to be robust against multiple spaces/newlines
  if (
    /^CREATE\s+(OR\s+REPLACE\s+)?VIEW/i.test(trimmedSql) ||
    /^DROP\s+VIEW/i.test(trimmedSql) ||
    /^DESCRIBE/i.test(trimmedSql) ||
    /^DESC\s+/i.test(trimmedSql) ||
    /^DESC$/i.test(trimmedSql) ||
    /^PRAGMA/i.test(trimmedSql)
  ) {
    return true
  }

  const sqlPreview = sql.length > 100 ? `${sql.substring(0, 100)}...` : sql

  if (!upperSql.startsWith('SELECT') && !upperSql.startsWith('WITH')) {
    throw new Error(`Only SELECT and WITH statements are allowed. Received: ${sqlPreview}`)
  }

  const forbiddenKeywords = [
    'DROP',
    'DELETE',
    'INSERT',
    'UPDATE',
    // 'CREATE', // Allowed for Views (checked above for start)
    'ALTER',
  ]
  for (const keyword of forbiddenKeywords) {
    if (upperSql.includes(` ${keyword} `)) {
      throw new Error(
        `Execution of forbidden SQL keyword "${keyword}" is disabled. SQL: ${sqlPreview}`
      )
    }
  }
  // Explicitly check for CREATE in the middle if it's not a view creation
  if (
    upperSql.includes(' CREATE ') &&
    !/^CREATE\s+(OR\s+REPLACE\s+)?VIEW/i.test(trimmedSql)
  ) {
    throw new Error(`Execution of forbidden SQL keyword "CREATE" is disabled. SQL: ${sqlPreview}`)
  }

  return true
}

/**
 * Executes a SQL query generated by the AI and returns the result.
 *
 * @param sql The SQL query string to execute.
 * @param databaseService The DatabaseService instance.
 * @returns A promise that resolves to the query result data.
 */
export async function executeSQL(
  sql: string,
  databaseService: NativeDatabaseService
): Promise<{
  data: Record<string, unknown>[]
  columnFields: Array<{ name: string; type: string }>
}> {
  validateSQL(sql)

  try {
    const result = await databaseService.queryWithSchema(sql)
    return result
  } catch (error) {
    console.error('SQL Execution Error:', error)
    throw error
  }
}
